In [1]:
import pandas as pd
import numpy as np

In [2]:
yelp_data = pd.read_csv('yelp_business.csv')
yelp_data.head()

,business_id,name,neighborhood,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,categories
0,FYWN1wneV18bWNgQjJ2GNg,"""Dental by Design""",NaN,"""4855 E Warner Rd, Ste B9""",Ahwatukee,AZ,85044,33.330690,-111.978599,4.0,22,1,Dentists;General Dentistry;Health & Medical;Or...
1,He-G7vWjzVUysIKrfNbPUQ,"""Stephen Szabo Salon""",NaN,"""3101 Washington Rd""",McMurray,PA,15317,40.291685,-80.104900,3.0,11,1,Hair Stylists;Hair Salons;Men's Hair Salons;Bl...
2,KQPW8lFf1y5BT2MxiSZ3QA,"""Western Motor Vehicle""",NaN,"""6025 N 27th Ave, Ste 1""",Phoenix,AZ,85017,33.524903,-112.115310,1.5,18,1,Departments of Motor Vehicles;Public Services ...
3,8DShNS-LuFqpEWIp0HxijA,"""Sports Authority""",NaN,"""5000 Arizona Mills Cr, Ste 435""",Tempe,AZ,85282,33.383147,-111.964725,3.0,9,0,Sporting Goods;Shopping
4,PfOCPjBrlQAnz__NXj9h_w,"""Brick House Tavern + Tap""",NaN,"""581 Howe Ave""",Cuyahoga Falls,OH,44221,41.119535,-81.475690,3.5,116,1,American (New);Nightlife;Bars;Sandwiches;Ameri...

In [7]:
states = yelp_data['state'].unique()
print(states)

['AZ' 'PA' 'OH' 'BW' 'NV' 'ON' 'NC' 'WI' 'SC' 'QC' 'IL' 'MLN' 'EDH' 'FIF'
 'CHE' 'CO' 'NYK' 'NE' 'HLD' 'WLN' 'ABE' 'WA' 'SCB' 'KHL' 'ESX' 'CMA' 'FAL'
 'ELN' 'NY' 'PKN' 'ST' '01' 'CA' 'NLK' 'GLG' 'C' 'VS' 'IN' 'XGL' 'AL' 'STG'
 'VT' 'CS' '30' 'AR' 'SL' 'NI' 'BY' 'AK' 'FLN' nan 'FL' 'MN' '6' 'NTH' 'MT'
 'B' 'GA' 'VA' 'DE' 'AB' 'HU' 'KY' '3' 'TAM' 'ZET' 'RCC' 'WHT']

In [9]:
count = yelp_data['state'].value_counts()
print(count)

AZ     52214
NV     33086
ON     30208
NC     12956
OH     12609
PA     10109
QC      8169
WI      4754
EDH     3795
BW      3118
IL      1852
SC       679
MLN      208
HLD      179
NYK      152
CHE      143
FIF       85
ELN       47
WLN       38
C         28
NY        18
ESX       12
ST        11
NI        10
01        10
VS         7
SCB        5
CA         5
XGL        4
BY         4
       ...
VT         2
CO         2
NTH        2
KY         1
FAL        1
B          1
MN         1
NE         1
DE         1
NLK        1
ZET        1
PKN        1
GA         1
FL         1
MT         1
STG        1
HU         1
AK         1
AL         1
RCC        1
CS         1
30         1
WHT        1
VA         1
3          1
AB         1
TAM        1
WA         1
SL         1
KHL        1
Name: state, Length: 67, dtype: int64

In [11]:
cities = yelp_data['city'].value_counts()
print(cities)

Las Vegas                        26775
Phoenix                          17213
Toronto                          17206
Charlotte                         8553
Scottsdale                        8228
Pittsburgh                        6355
Mesa                              5760
Montr√©al                          5709
Henderson                         4465
Tempe                             4263
Chandler                          3994
Edinburgh                         3868
Cleveland                         3322
Madison                           3213
Glendale                          3206
Gilbert                           3128
Mississauga                       2726
Stuttgart                         2000
Peoria                            1706
Markham                           1564
North Las Vegas                   1393
Champaign                         1195
Scarborough                       1095
North York                        1092
Surprise                          1018
Richmond Hill                      888
Concord                            864
Brampton                           839
Goodyear                           772
Vaughan                            768
                                 ...
Mint  Hill                           1
L√ºbeck                               1
Sunnyslope                           1
Mt Albert                            1
Las Vegas East                       1
Saint Leonard                        1
Fisher                               1
Mayfield Hts                         1
Les Coteaux                          1
Forest Grove                         1
Wharton                              1
West Lothian                         1
Strongville                          1
Centre Island                        1
Massey                               1
San Rafael                           1
Regional Municipality of York        1
Phoenix metro area                   1
Charlotte (University)               1
L'√éle-Bizard                         1
Mayfield Hts.                        1
Laval, Pont Viau                     1
St. Jean Sur Richelieu               1
Northbrook                           1
Clark County                         1
North Braddock                       1
Topaz                                1
Gillbert                             1
Stuttgart - Bad Cannstatt            1
Glendale Az                          1
Name: city, Length: 1093, dtype: int64

In [14]:
print(cities['Pittsburgh'])

6355

In [15]:
#todo pittsburgh
#clean is_open
#filter based on city
#add categories to business
#find averages based on users per categories
# 1 = open, 0 = closed
open_businesses = yelp_data[yelp_data['is_open']==1]
open_businesses.head()

,business_id,name,neighborhood,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,categories
0,FYWN1wneV18bWNgQjJ2GNg,"""Dental by Design""",NaN,"""4855 E Warner Rd, Ste B9""",Ahwatukee,AZ,85044,33.330690,-111.978599,4.0,22,1,Dentists;General Dentistry;Health & Medical;Or...
1,He-G7vWjzVUysIKrfNbPUQ,"""Stephen Szabo Salon""",NaN,"""3101 Washington Rd""",McMurray,PA,15317,40.291685,-80.104900,3.0,11,1,Hair Stylists;Hair Salons;Men's Hair Salons;Bl...
2,KQPW8lFf1y5BT2MxiSZ3QA,"""Western Motor Vehicle""",NaN,"""6025 N 27th Ave, Ste 1""",Phoenix,AZ,85017,33.524903,-112.115310,1.5,18,1,Departments of Motor Vehicles;Public Services ...
4,PfOCPjBrlQAnz__NXj9h_w,"""Brick House Tavern + Tap""",NaN,"""581 Howe Ave""",Cuyahoga Falls,OH,44221,41.119535,-81.475690,3.5,116,1,American (New);Nightlife;Bars;Sandwiches;Ameri...
5,o9eMRCWt5PkpLDE0gOPtcQ,"""Messina""",NaN,"""Richterstr. 11""",Stuttgart,BW,70567,48.727200,9.147950,4.0,5,1,Italian;Restaurants

In [17]:
open_pitt = open_businesses[open_businesses['city'] == 'Pittsburgh']
open_pitt.head()

,business_id,name,neighborhood,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,categories
75,o1fTwfqN0sDFNpV1CkOPPg,"""Crazy Mocha Coffee""",Lawrenceville,"""4032 Butler St""",Pittsburgh,PA,15201,40.469295,-79.961273,3.5,16,1,Restaurants;Sandwiches;Coffee & Tea;Food
76,-nHkhiuerqmfBG3v2v9O-g,"""Bruegger's Bagels""",NaN,"""5217 Clairton Blvd""",Pittsburgh,PA,15236,40.344194,-79.970963,2.5,5,1,Breakfast & Brunch;Bagels;Restaurants;Bakeries...
98,HcEJ2YiSLX_mT3RE0hvKWQ,"""Blush""",Downtown,"""135 9th St""",Pittsburgh,PA,15222,40.444236,-79.998325,3.0,21,1,Nightlife;Adult Entertainment;Strip Clubs
109,shNBn6mTKxZ124yPC_H02Q,"""T.W.Tile""",NaN,"""248 Tara Dr""",Pittsburgh,PA,15236,40.327956,-79.960479,3.5,3,1,Kitchen & Bath;Countertop Installation;Home Se...
178,mLP-jIIRdoaYM7fJqqFurw,"""Napoli Pizzeria""",Squirrel Hill,"""2006 Murray Ave""",Pittsburgh,PA,15217,40.434399,-79.922983,4.0,53,1,Italian;Pizza;Restaurants;Salad